[package]
edition = "2021"
name = "canisters"
version = "0.1.0"

[dependencies]
async-trait = "0.1"
candid = "0.7"
hex = "0.4"
ic-cdk = "0.3"
num-traits = "0.2"
serde = "1.0"
serde_json = "1.0"
sha2 = "0.10"
